# BigQuery SQL example

In [1]:
% load_ext google.cloud.bigquery

from google.cloud import bigquery

In [2]:
sql = """
    SELECT * 
    FROM `bigquery-public-data.ethereum_blockchain.transactions` AS transactions
    LIMIT 10
"""

In [3]:
client = bigquery.Client()

In [4]:
df = client.query(sql).to_dataframe()

In [5]:
df.head()

,hash,nonce,transaction_index,from_address,to_address,value,gas,gas_price,input,receipt_cumulative_gas_used,receipt_gas_used,receipt_contract_address,receipt_root,receipt_status,block_timestamp,block_number,block_hash
0,0x6d48f26fd42997fac0e8184e9ec6d0083c45178f0b1e...,1,1,0x009e641f4f1f5557a8c4ea260b10c394e2f36c91,0x000ccb3de50dabdf4cd5fcbb48868cd5b58b4c2d,480000000000000000,21000,10000000000000,0x,42000,21000,None,0x498dfc7f79b2d5d12a61fcff4fddca346825fecd3455...,None,2015-10-10 02:13:16+00:00,360192,0xe674e5ee29e76759292867d468b4dea778989f25953f...
1,0x2b8208a93774c49a28b96ffc0e089863c423202fbfef...,1,2,0x004b878a2bf81783569e92c9769d9528d3641d5f,0x000ccb3de50dabdf4cd5fcbb48868cd5b58b4c2d,480000000000000000,21000,10000000000000,0x,63000,21000,None,0x6d4837368700f006cd2a3cc59097d1ad67306f995743...,None,2015-10-10 02:13:16+00:00,360192,0xe674e5ee29e76759292867d468b4dea778989f25953f...
2,0xd023acdcc72daf74bd043b251be1a9a5eb24b1afcc8e...,1,0,0x00a5a2ab587d9fdac8fa5af0f5512764140200ad,0x000ccb3de50dabdf4cd5fcbb48868cd5b58b4c2d,480000000000000000,21000,10000000000000,0x,21000,21000,None,0xecad33e212473159ade5db875da715805598705d4e4f...,None,2015-10-10 02:13:16+00:00,360192,0xe674e5ee29e76759292867d468b4dea778989f25953f...
3,0x215d7cdb1755e7424efe47371516d83bce8abbd69abd...,4,3,0x00427c0a656d17a9e93f0d411e7708bfc95cec14,0x000ccb3de50dabdf4cd5fcbb48868cd5b58b4c2d,480000000000000000,21000,10000000000000,0x,84000,21000,None,0xeb753a5a9cf6f1e7dadbb58f40f07045f4547933d1a1...,None,2015-10-10 02:13:16+00:00,360192,0xe674e5ee29e76759292867d468b4dea778989f25953f...
4,0x9a41a866862eed42cfaca12f2f9bc2cd3a7ff0aba76c...,141,5,0x31191beeb5a3d7f5ebc5b193e98bd15ce10eb249,0x32be343b94f860124dc4fee278fdcbd38c102d88,2445612670000000000,21000,50000000000,0x,343829,21000,None,0xc6bcfa6da873fd1d6e05179064fb3cffb85c75eec5cd...,None,2015-10-10 03:40:18+00:00,360448,0x29ffcc37ffe3abad1ff1c2ba73e12c8921867d767744...